name: Build
on:
  - push
  - pull_request
concurrency:
  group: ${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --shm-size 512mb
    steps:
      - uses: actions/checkout@v4
      - name: Prepare container
        run: |
          pacman --sync --noconfirm --refresh --sysupgrade
          pacman --sync --noconfirm sudo
          useradd --user-group --create-home builder
          echo "builder ALL=(ALL:ALL) NOPASSWD:ALL" | \
            EDITOR=tee visudo -f /etc/sudoers.d/groonga
      - name: Install dependencies
        run: |
          pacman --sync --noconfirm --refresh --sysupgrade
          pacman --sync --noconfirm \
            autoconf \
            debugedit \
            fakeroot \
            gcc \
            git \
            make
      - name: Install dependencies in AUR
        run: |
          dependencies=(
            mecab-git
            mecab-ipadic
          )
          for package in "${dependencies[@]}"; do
            sudo -u builder git clone --depth=1 "https://aur.archlinux.org/${package}.git" "/home/builder/${package}"
            pushd "/home/builder/${package}"
            sudo -u builder makepkg \
              --install \
              --needed \
              --noconfirm \
              --rmdeps \
              --skipchecksums \
              --skippgpcheck \
              --syncdeps
            popd
            rm -rf "/home/builder/${package}"
          done
      - name: Build package
        run: |
          sudo -u builder git clone --depth=1 https://aur.archlinux.org/groonga.git /home/builder/groonga
          pushd /home/builder/groonga
          sudo -u builder makepkg \
            --needed \
            --noconfirm \
            --rmdeps \
            --skippgpcheck \
            --syncdeps
          popd
      - name: Test install
        run: |
          pacman --needed --noconfirm --upgrade /home/builder/groonga/groonga-*.pkg.tar.zst
      - name: Test if groonga command is executable
        run: groonga --version
      - uses: actions/upload-artifact@v4
        with:
          name: packages
          path: "/home/builder/groonga/*.pkg.tar.*"
