name: Pakcage
on:
  - push
  - pull_request
concurrency:
  group: ${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  packages:
    name: Pakcages
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --shm-size 512mb
    steps:
      - uses: actions/checkout@v4
      - name: Prepare container
        run: |
          pacman --sync --noconfirm --refresh --sysupgrade
          pacman --sync --noconfirm sudo
          useradd --user-group --create-home builder
          echo "builder ALL=(ALL:ALL) NOPASSWD:ALL" | \
            EDITOR=tee visudo -f /etc/sudoers.d/groonga
      - name: Install dependencies
        run: |
          pacman --sync --noconfirm --refresh --sysupgrade
          pacman --sync --noconfirm \
            autoconf \
            debugedit \
            fakeroot \
            gcc \
            git \
            make
      - name: Install dependencies in AUR
        run: |
          dependencies=(
            mecab-git
            mecab-ipadic
          )
          for package in "${dependencies[@]}"; do
            sudo -u builder git clone --depth=1 "https://aur.archlinux.org/${package}.git" "/home/builder/${package}"
            pushd "/home/builder/${package}"
            sudo -u builder makepkg \
              --install \
              --needed \
              --noconfirm \
              --rmdeps \
              --syncdeps
            popd
            rm -rf "/home/builder/${package}"
          done
      - name: Import public key
        run: sudo -u builder gpg --recv-key 624CF77434839225
      - name: Build package
        run: |
          sudo -u builder git clone --depth=1 https://aur.archlinux.org/groonga.git /home/builder/groonga
          pushd /home/builder/groonga
          sudo -u builder makepkg \
            --needed \
            --noconfirm \
            --rmdeps \
            --syncdeps
          popd
      - name: Test install
        run: |
          pacman --needed --noconfirm --upgrade /home/builder/groonga/groonga-*.pkg.tar.zst
      - name: Test if groonga command is executable
        run: groonga --version
      - uses: actions/upload-artifact@v4
        with:
          name: packages
          path: "/home/builder/groonga/*.pkg.tar.*"
  release:
    name: Release
    needs: packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
      - name: Prepare release note
        run: |
          echo "Groonga ${GITHUB_REF_NAME}" | tee release-title.txt
          commit_id=$(git ls-remote  https://aur.archlinux.org/groonga.git HEAD | head -n 1 | awk '{print $1}')
          cat <<RELEASE_NOTE | tee release-note.md
          Groonga: https://github.com/groonga/groonga/releases/tag/v${GITHUB_REF_NAME}
          AUR: https://aur.archlinux.org/packages/groonga
          PKGBUILD: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=groonga&id=${commit_id}
          RELEASE_NOTE
      - name: Create GitHub Release
        if: github.ref_type == 'tag'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${GITHUB_REF_NAME}" \
            --discussion-category Announcements \
            --notes-file release-note.md \
            --repo "${GITHUB_REPOSITORY}" \
            --title "$(cat release-title.txt)" \
            packages/*
